version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3307:3306'
    environment:
       MYSQL_DATABASE: 'rdf'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'qwerty12345.A'
       MYSQL_ROOT_PASSWORD: 'qwerty12345.A'
